version: '3'
services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    
  cars1:
    build: ./
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:12345@host.docker.internal:5433/cars?schema=public
    links:
      - postgres

  cars2:
    build: ./
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:12345@host.docker.internal:5433/cars?schema=public
    links:
      - postgres
  
 

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:80"
    depends_on:
      - cars1
      - cars2
      - postgres