name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: cars
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker-compose -f docker-compose.yml build

      - name: Apply Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          PORT: ${{ vars.PORT }}

      - name: Run tests
        run: npm run test

      - name: Deploy application
        run: docker-compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec $(docker ps -qf "name=postgres") pg_isready -U your_db_user; do
            sleep 1
          done

      - name: Run application
        run: npm start
